# Generated by Django 5.2.8 on 2025-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_play_actors_play_directors_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plays'),
        ),
    ]
